# Generated by Django 5.0 on 2023-12-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('email', models.CharField()),
                ('password', models.CharField()),
                ('address', models.CharField()),
                ('phone', models.CharField()),
            ],
        ),
    ]
