# Generated by Django 5.0 on 2024-02-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='picture',
            field=models.ImageField(default=0, upload_to='menu/'),
            preserve_default=False,
        ),
    ]
