# Generated by Django 5.0 on 2024-02-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdata',
            name='ownername',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantdata',
            name='picture',
            field=models.ImageField(default=1, upload_to='restaurant/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurantdata',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantdata',
            name='delivery_time',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='restaurantdata',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurantdata',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
    ]
