# Generated by Django 5.0 on 2024-02-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurantdata_ownername_restaurantdata_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdata',
            name='description',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantdata',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
