# Generated by Django 5.0 on 2024-02-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurantdata_description_restaurantdata_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdata',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
