# Generated by Django 5.0 on 2024-02-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_restaurantdata_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdata',
            name='description',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantdata',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
