# Generated by Django 5.0 on 2024-03-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_restaurantdata_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantdata',
            old_name='username',
            new_name='username_key',
        ),
    ]
