# Generated by Django 5.0 on 2024-03-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_rename_username_restaurantdata_username_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantdata',
            name='username_key',
        ),
    ]
