# Generated by Django 5.0 on 2024-03-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_remove_restaurantdata_username_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heading',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='RestaurantData',
        ),
    ]
