# Generated by Django 5.0 on 2024-03-03 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_remove_heading_restaurant_delete_restaurantdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('ownername', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=15)),
                ('delivery_time', models.CharField(max_length=5)),
                ('picture', models.ImageField(upload_to='restaurant/')),
                ('description', models.TextField(max_length=500)),
                ('open', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='heading',
            name='restaurant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantdata'),
            preserve_default=False,
        ),
    ]
