# Generated by Django 5.0 on 2024-03-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_restaurantdata_heading_restaurant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestaurantData',
            new_name='RestaurantUser',
        ),
    ]
