# Generated by Django 5.0 on 2024-03-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_rename_restaurantdata_restaurantuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantuser',
            name='picture',
            field=models.ImageField(upload_to='restaurant/images'),
        ),
    ]
