# Generated by Django 5.0 on 2024-03-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_alter_restaurantuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantuser',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
