# Generated by Django 5.0 on 2024-03-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_alter_restaurantuser_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantuser',
            name='coverphoto',
            field=models.ImageField(default=0, upload_to='coverphotos/'),
            preserve_default=False,
        ),
    ]
