# Generated by Django 5.0 on 2024-04-04 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_remove_order_cart_remove_orderitem_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantuser'),
            preserve_default=False,
        ),
    ]
