# Generated by Django 5.0 on 2024-04-10 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_order_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='tags',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='tag',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restaurant.tags'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurantuser',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
