# Generated by Django 5.0 on 2024-05-01 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0027_promotionimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotionimage',
            old_name='images',
            new_name='picture',
        ),
    ]
