# Generated by Django 5.0 on 2024-03-03 03:19

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_admindata_options_remove_admindata_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='admindata',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='admindata',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admindata',
            name='picture',
            field=models.ImageField(default=0, upload_to='admins/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admindata',
            name='address',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='phonenumber',
            field=models.CharField(),
        ),
    ]
