# Generated by Django 5.0 on 2024-03-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_alter_admindata_managers_admindata_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admindata',
            options={},
        ),
        migrations.AlterModelManagers(
            name='admindata',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='username',
        ),
        migrations.AlterField(
            model_name='admindata',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='password',
            field=models.CharField(),
        ),
    ]
