# Generated by Django 5.0 on 2024-03-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_alter_admindata_options_alter_admindata_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admindata',
            options={},
        ),
        migrations.AlterModelManagers(
            name='admindata',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='admindata',
            name='username',
        ),
    ]
