# Generated by Django 5.0 on 2024-03-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_alter_admindata_options_alter_admindata_managers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminData',
            new_name='AdminUser',
        ),
    ]
