# Generated by Django 5.0 on 2024-04-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_rename_admindata_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
